[package]
name = "infra"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.32", features = ["bundled"] }
wgpu = "28.0.0"
pollster = "0.3" # async実行用
bytemuck = { version = "1.14", features = ["derive"] }
futures-intrusive = "0.5"
