[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
rng-core = { path = "../rng-core" }
serde_json = "1.0"
search = { path = "../search" }
clap = { version = "4", features = ["derive"] }
pollster = "0.3"
serde = { version = "1", features = ["derive"] }
