[package]
name = "white2-dragonite-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
search = { path = "../search" }
rng-core = { path = "../rng-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
pollster = "0.3"
